// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ZecvN8DlZgkvf945FlDEflVn9EJ_Rt4',
    appId: '1:865411092659:web:b971fabb748082972ba0c6',
    messagingSenderId: '865411092659',
    projectId: 'flutterfiretry',
    authDomain: 'flutterfiretry.firebaseapp.com',
    storageBucket: 'flutterfiretry.appspot.com',
    measurementId: 'G-51CQ1JRDEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0LK4MsVBi5E0Vlj083rk-zyN6eWjsFeE',
    appId: '1:865411092659:android:cf28cfd1335885452ba0c6',
    messagingSenderId: '865411092659',
    projectId: 'flutterfiretry',
    storageBucket: 'flutterfiretry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwEZA4RyQ27GPqdQm5jDcc_3uaDt-vejc',
    appId: '1:865411092659:ios:a3369dac11243bb42ba0c6',
    messagingSenderId: '865411092659',
    projectId: 'flutterfiretry',
    storageBucket: 'flutterfiretry.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwEZA4RyQ27GPqdQm5jDcc_3uaDt-vejc',
    appId: '1:865411092659:ios:32899e485f9708e22ba0c6',
    messagingSenderId: '865411092659',
    projectId: 'flutterfiretry',
    storageBucket: 'flutterfiretry.appspot.com',
    iosBundleId: 'com.example.flutterlist.RunnerTests',
  );
}
